version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cbomdb
      POSTGRES_USER: cbom
      POSTGRES_PASSWORD: cbom123
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cbomdb
      SPRING_DATASOURCE_USERNAME: cbom
      SPRING_DATASOURCE_PASSWORD: cbom123
    ports: ["8080:8080"]
    depends_on: [postgres]

  worker:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cbomdb
      SPRING_DATASOURCE_USERNAME: cbom
      SPRING_DATASOURCE_PASSWORD: cbom123
    command: ["java","-jar","/app/app.jar","--worker"]
    depends_on: [postgres]

volumes:
  pgdata:
